# This workflow will deploy a PowerShell project to an Azure Function App when a commit is pushed to main.
# The workflow can also be manually triggered using the "Run Workflow" button in the GitHub Actions UI.

name: AZD Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    # These variables are always set by `azd pipeline config`
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install azd
        uses: Azure/setup-azd@v2

      - name: Login with Azure Dev CLI
        run: |
          azd auth login `
            --client-id "$env:AZURE_CLIENT_ID" `
            --federated-credential-provider "github" `
            --tenant-id "$env:AZURE_TENANT_ID"
        shell: pwsh

      - name: Provision Infrastructure
        run: azd provision --no-prompt

      - name: Deploy Application
        run: azd hooks run postprovision --no-prompt
